### ISSUE TITLE
Error Scraping the CSV

### ISSUE THREAD

**Issue by fzalkow** [Spijkervet/eurovision-dataset#1]
I want to report an issue with scraping the CSV file.

Since I use Anaconda, I compiled an [environment file](https://gist.github.com/fzalkow/6680d2d73bf80582f33dc898030a7c69) for using your code. It contains several WebDriver packages.

I get the error message below if I try to create the CSV by myself. It seems to me that it is not a WebDriver issue, but an issue with the web scraper.

Since, meanwhile, I got the metadata from a colleague, it is not urgent for me anymore. Still this issue may be of interest for you.

```
$ python3 main.py --start 1956 --end 2019

Chrome WebDriver is missing
Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Scraping: Eurovision Song Contest 1956 final
1956 Switzerland final
1956 Netherlands final
1956 Switzerland final
1956 Belgium final
1956 Germany final
1956 France final
1956 Luxembourg final
1956 Italy final
1956 Netherlands final
1956 Belgium final
1956 Germany final
1956 France final
1956 Luxembourg final
1956 Italy final
https://eurovisionworld.com/eurovision/1956/switzerland
https://eurovisionworld.com/eurovision/1956/netherlands
https://eurovisionworld.com/eurovision/1956/belgium
https://eurovisionworld.com/eurovision/1956/germany
https://eurovisionworld.com/eurovision/1956/france
https://eurovisionworld.com/eurovision/1956/luxembourg
https://eurovisionworld.com/eurovision/1956/italy
https://eurovisionworld.com/eurovision/1956/netherlands2
https://eurovisionworld.com/eurovision/1956/belgium2
https://eurovisionworld.com/eurovision/1956/germany2
https://eurovisionworld.com/eurovision/1956/france2
https://eurovisionworld.com/eurovision/1956/italy2
Scraping: Eurovision Song Contest 1957 final
1957 Netherlands final
1957 France final
1957 Denmark final
1957 Luxembourg final
1957 Germany final
1957 Italy final
1957 United KingdomUK final
1957 Belgium final
1957 Switzerland final
1957 Austria final
https://eurovisionworld.com/eurovision/1957/netherlands
https://eurovisionworld.com/eurovision/1957/france
https://eurovisionworld.com/eurovision/1957/denmark
https://eurovisionworld.com/eurovision/1957/luxembourg
https://eurovisionworld.com/eurovision/1957/germany
https://eurovisionworld.com/eurovision/1957/italy
https://eurovisionworld.com/eurovision/1957/united-kingdom
https://eurovisionworld.com/eurovision/1957/belgium
https://eurovisionworld.com/eurovision/1957/switzerland
https://eurovisionworld.com/eurovision/1957/austria
Scraping: Eurovision Song Contest 1958 final
1958 France final
1958 Switzerland final
1958 Italy final
1958 Sweden final
1958 Belgium final
1958 Austria final
1958 Germany final
1958 Denmark final
1958 Netherlands final
1958 Luxembourg final
https://eurovisionworld.com/eurovision/1958/france
https://eurovisionworld.com/eurovision/1958/switzerland
https://eurovisionworld.com/eurovision/1958/italy
https://eurovisionworld.com/eurovision/1958/sweden
https://eurovisionworld.com/eurovision/1958/belgium
https://eurovisionworld.com/eurovision/1958/austria
https://eurovisionworld.com/eurovision/1958/germany
https://eurovisionworld.com/eurovision/1958/denmark
https://eurovisionworld.com/eurovision/1958/netherlands
https://eurovisionworld.com/eurovision/1958/luxembourg
Scraping: Eurovision Song Contest 1959 final
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    contest = get_contest(y, rounds)
  File "main.py", line 12, in get_contest
    contest = scraper.scrape_year(contest, r)
  File "/home/fzalkow/alabs_mountpoints/groupmm/Data/AudioDB/Eurovision/eurovision_dataset-master/scraper.py", line 128, in scrape_year
    rows = voting_table.find('table').find('tbody').findAll('tr')
AttributeError: 'NoneType' object has no attribute 'find' 
```

**Comment by Spijkervet** [comment]
I fixed this due to website changes
